# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    MANUAL_DELETION_ENABLED: true
    EVENT_OBFUSCATION_ENABLED: true
    CASE_EXPIRY_DELETION_ENABLED: true
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    DARTS_GATEWAY_URL: http://darts-gateway.staging.platform.hmcts.net
    ARM_URL: http://darts-stub-services.staging.platform.hmcts.net
    FEIGN_LOG_LEVEL: none
    IS_MOCK_ARM_RPO_DOWNLOAD_CSV: false
    ARM_RPO_THREAD_SLEEP_DURATION: 5s
